### ISSUE TITLE
TODO: couple of changes

### ISSUE THREAD

**Issue by MarcoForte** [MarcoForte/closed-form-matting#4]
- [x] CLI interface for alpha matting
- [x] Change to use opencv not scipy.misc as it's deprecated
- [x] Add fg/bg reconstruction image to readme
- [x] Change to use trimap not scribble
